---
- name: Install mDNS configuration
  ansible.builtin.copy:
    src: "../files/etc/systemd/resolved.conf.d/mDNS.conf"
    dest: "/etc/systemd/resolved.conf.d/mDNS.conf"
    owner: root
    group: root
    mode: '0644'
