---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ optional_packages }}"
    state: present

- name: Append package list
  ansible.builtin.include_tasks: util/append-packages.yml
  with_items:
    - ["{{ optional_packages }}"]
