---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ linux_packages }}"
    state: present

- name: Append package list
  ansible.builtin.include_tasks: util/append-packages.yml
  with_items:
    - ["{{ linux_packages }}"]

- name: Load WiFi module
  ansible.builtin.copy:
    src: "files/etc/modules-load.d/brcmfmac.conf"
    dest: "/etc/modules-load.d/brcmfmac.conf"
    owner: root
    group: root
    mode: '0644'
