---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ make_packages }}"
    state: present

- name: Append package list
  ansible.builtin.include_tasks: util/append-packages.yml
  with_items:
    - ["{{ make_packages }}"]
