---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ bluetooth_packages }}"
    state: present

- name: Append package list
  ansible.builtin.include_tasks: util/append-packages.yml
  with_items:
    - ["{{ bluetooth_packages }}"]

- name: Install headset configuration
  ansible.builtin.copy:
    src: "files/etc/bluetooth/audio.conf"
    dest: "/etc/bluetooth/audio.conf"
    owner: root
    group: root
    mode: '0644'
