---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ ansible_packages }}"
    state: present

- name: Append package list
  ansible.builtin.include_tasks: util/append-packages.yml
  with_items:
    - ["{{ ansible_packages }}"]

- name: Install hosts file
  ansible.builtin.copy:
    src: "../files/hosts"
    dest: "/etc/ansible/hosts"
    owner: root
    group: root
    mode: '0644'
